# Generated by Django 4.1.2 on 2023-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_postdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
