# Generated by Django 4.1.2 on 2023-09-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
