# Generated by Django 4.1.2 on 2023-11-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_postcomments_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'Editor'), ('2', 'Author'), ('3', 'Subscriber')], default='3', max_length=20),
        ),
    ]
